### ISSUE TITLE
[Quest][NPC] Amped for Revolt! & Basic Chemistry - Gargoyle Ambusher & Frostbrood Sentry

### ISSUE THREAD

**Issue by staylifted123** [GameFreedomGG/Sindragosa#193]
Decription: Gargoyle Ambusher and Frostbrood Sentry are not spawning during Amped for Revolt! and Basic Chemistry

How it works: Gargoyle Ambusher and Frostbrood Sentry not spawning during Amper for Revolt! and Basic Chemistry

How it should work: https://www.youtube.com/watch?v=_8U7Z5Shbhg

Source (you should point out proofs of your report, please give us some source):

Quest is in Icecrown

The quests were added in patch 3.3.0.10958

This is probably the issue. We are in patch 3.0.2

**Comment by staylifted123** [comment]
In Icecrown

**Comment by staylifted123** [comment]
The quests were added in patch 3.3.0.10958    

This is probably the issue.

**Comment by MrTide** [comment]
These two quests were Added in patch 3.3.0 i am not sure if its intended content wise since there are some quests that are available as well while they shouldn't thats for the devs to decide

Checked the creatures 
 Frostbrood Sentry are ingame
but
Gargoyle Ambusher are missing 

![image](https://user-images.githubusercontent.com/36106057/148935450-b5aa1012-f90e-4e85-aa0e-ff366a8ed19a.png)

https://github.com/GameFreedomGG/Sindragosa/issues/309
