### ISSUE TITLE
[NPC][Item] Deviate Creepers - Crisp Spider Meat

### ISSUE THREAD

**Issue by Gorgonic** [GameFreedomGG/Sindragosa#27]
Deviate Creepers in the entrance tunnel to the Wailing Caverns are dropping Crisp Spider Meat rather than raptor meat

**Comment by MrTide** [comment]
![image](https://user-images.githubusercontent.com/36106057/149621069-3d6456f9-277d-451e-955a-45b3153a8642.png)
Player is right but multiple databases show that it should drop but wowhead says otherwise
https://tbc.wowhead.com/npc=3632/deviate-creeper
https://wotlk.evowow.com/?npc=3632#drops
dropping spider meat from raptors sure doesn't look right
