### ISSUE TITLE
[Hunter][Talent] Lock and Load

### ISSUE THREAD

**Issue by HunterTester** [GameFreedomGG/Sindragosa#306]
Decription:
Lock and Load (Survival Talent) in the 4th tree currently proccs when frost trapping mobs that are immune to snare or slows such as raidbosses.

How it works:
Lock and Load (Survival Talent) in the 4th tree currently proccs when frost trapping mobs that are immune to snare or slows such as raidbosses.

How it should work:
It should only proc on slowable mobs such as adds

Source (you should point out proofs of your report, please give us some source):
Patch 3.2.0 (04-Aug-2009): Now has a 22 second cooldown. The Lock and Load effect cannot be obtained on targets immune to snare effects when Frost Trap is used.

**Comment by HunterTester** [comment]
https://wowwiki-archive.fandom.com/wiki/Lock_and_Load

**Comment by dreamk33per** [comment]
Patch 3.2.0 (04-Aug-2009): Now has a 22 second cooldown. The Lock and Load effect cannot be obtained on targets immune to snare effects when Frost Trap is used. The tooltip for this talent has been updated to indicate that it also works with Explosive Trap.

It is only for patch 3.2 which is ToC

**Comment by HunterTester** [comment]
Game is played on 3.3.5a talents.

**Comment by HunterTester** [comment]
I don't, but a bugtracker is for tracking bugs no?
kinda unfair for other specs that survival gets to exploit a bunch of bugs that go in their favour on this particular server no?

**Comment by dreamk33per** [comment]
This talent allows SV hunters to play differently than the other two specs, going in melee range to place traps and then going back to ranged spot. Making this talent don't proc on bosses will basically chase away the people who enjoys it. You consider it a bug, but this is a private server and if you dont like it you can go to retail/classic. This talent shoud stay as it is or every hunter is going to quit the server and there are lots of huners atm.

**Comment by HunterTester** [comment]
You're making a whole bunch of assumptions there, but I suppose other classes that have 3.2.0 talents nerfed should get them back as well huh? Destro warlock Conflag critting for 80% health comes to mind for example, might aswell make them meta too cuz its more fun :DDD

**Comment by dreamk33per** [comment]
You are the one making an assumption that everything should be 100% blizzlike on a private server. Warmane, Sunwell, Whitemane, Tauri... on all of then the LnL was proccing off bosses and wasnt a problem. Play your bugged MM spec atm that deals double the supposed damage and enjoy life

**Comment by HunterTester** [comment]
LnL did not procc off bosses on any of those servers. that was the whole reason top hunters were stacking up on repair bots to frost arrow them and proc lock and load.

you're blatanly lying now just to try and make a point enjoy life

**Comment by dreamk33per** [comment]
I was playing on all of the said servers and LnL was proccing of bosses till RS. You are the one lying

**Comment by HunterTester** [comment]
Sure, just not 100% of the time with frost trap.

**Comment by dreamk33per** [comment]
One talent that does not break the game, but makes more fun, does not mean that the server is emulated on patch 3.2. As I said go play your bugged MM spec that is doing double the dps that it is supposed to or I am going to report it and you will cry even more.

**Comment by HunterTester** [comment]
I play both specs, feel free to report the broken MM stuff you find, that's what the github is for

**Comment by dreamk33per** [comment]
There is no way you play SV spec. Another lie. No sane person that plays SV will report as bug the thing that makes the spec so fun and different from the other two specs. Also it was like that since the dawn of WotlK private servers. This talent working like that havent break any private server before so you should not worry. Go back to retail/classic if you don't like it.

**Comment by HunterTester** [comment]
Of course I play it, it's busted? hello?

**Comment by dreamk33per** [comment]
MM is busted atm not SV. SV is a spec that has no scaling and it's good early on when people has low ilvl gear. Your statement makes no sense once again.

**Comment by HunterTester** [comment]
Have a nice day

**Comment by dreamk33per** [comment]
Thanks.

**Comment by Soufly** [comment]
LnL does NOT proc under any of the wotlk bosses in naxx/eoe/os with frost trap.

**Comment by HunterTester** [comment]
> 

Try it out m8

**Comment by Soufly** [comment]
This issue is connected with the talent % for LnL.Basically using 1/3 points on LnL gives u way higher chance than 33%.Same goes for explosive trap/black arrow.

**Comment by Soufly** [comment]
This should have priority,since is an exploit as well @Game-Freedom

**Comment by Soufly** [comment]
How it should work:
LnL 1/3 = Explosive trap,20% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 2/3 = Explosive trap,40% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 3/3 = Explosive trap,60% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
Black Arrow LnL - 1/3 = 10%
Black Arrow LnL - 2/3 = 20%
Black Arrow LnL - 3/3 = 30%

**Comment by Soufly** [comment]
How it should work:
LnL 1/3 = Explosive trap,20% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 2/3 = Explosive trap,40% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 3/3 = Explosive trap,60% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
Black Arrow LnL - 1/3 = 10%
Black Arrow LnL - 2/3 = 20%
Black Arrow LnL - 3/3 = 30%

Cannot be obtained on targets immune to snare effects when Frost Trap is used.(82+ level mobs,also few with other that are 80/81).

**Comment by Soufly** [comment]
How it should work:
LnL 1/3 = Explosive trap,20% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 2/3 = Explosive trap,40% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 3/3 = Explosive trap,60% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
Black Arrow LnL (for its total duration) - 1/3 = 10%
Black Arrow LnL (for its total duration) - 2/3 = 20%
Black Arrow LnL (for its total duration) - 3/3 = 30%

Cannot be obtained on targets immune to snare effects when Frost Trap is used.(82+ level mobs and not only).

**Comment by MrTide** [comment]
It didn't change until panda expansion so i believe it should not proc in any way.
Patch 5.1.0 (27-Nov-2012): Lock and Load will now activate correctly when Ice Trap is triggered by an immune target, as long as a susceptible target is within the area of effect.

**Comment by Godmatik** [comment]
So will this be changed or will the talent be kept the same function?

**Comment by UltraNix** [comment]
@Godmatik ?? The Lock and Load will not proc if target was immune.

**Comment by Soufly** [comment]
Still procs from bosses,if its not live.

**Comment by Godmatik** [comment]
Yes I see it was just pushed to live realm
