### ISSUE TITLE
[Hunter][Talent] Lock and Load

### ISSUE THREAD

**Issue by HunterTester** [GameFreedomGG/Sindragosa#307]
Decription: Speccing 1/3 lock and load makes it so your Black Arrow proccs faster than if you were to spec it fully.

How it works:
 Speccing 1/3 lock and load makes it so your Black Arrow proccs faster than if you were to spec it fully.

How it should work:
It should proc less, not more
Source (you should point out proofs of your report, please give us some source):
Go to target dummy, spec 1/3 and 3/3 notice the difference between procc rate

**Comment by Soufly** [comment]
Incorrect,and also i dont see a proof ?

**Comment by Soufly** [comment]
Confirmed.

**Comment by Soufly** [comment]
Should be high priority! Fix it before ulduar..

**Comment by Soufly** [comment]
How it should work:
LnL 1/3 = Explosive trap,20% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 2/3 = Explosive trap,40% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 3/3 = Explosive trap,60% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
Black Arrow LnL - 1/3 = 10%
Black Arrow LnL - 2/3 = 20%
Black Arrow LnL - 3/3 = 30%

Cannot be obtained on targets immune to snare effects when Frost Trap is used.(82+ level mobs,also few with other that are 80/81).

**Comment by Soufly** [comment]
How it should work:
LnL 1/3 = Explosive trap,20% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 2/3 = Explosive trap,40% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
LnL 3/3 = Explosive trap,60% chance for its total duration PER TARGET(since the trap does aoe damage.the initial damage/hit does not count)
Black Arrow LnL (for its total duration)  - 1/3 = 10%
Black Arrow LnL (for its total duration)  - 2/3 = 20%
Black Arrow LnL (for its total duration) - 3/3 = 30% 

Cannot be obtained on targets immune to snare effects when Frost Trap is used.(82+ level mobs and not only).

**Comment by Soufly** [comment]
@UltraNix is this live ? I did testing few minutes ago and is still bugged.

**Comment by UltraNix** [comment]
With new update should be okay.

**Comment by Soufly** [comment]
It is working with Explosive Trap/black arrow..... but still Frost Trap insta proc it.

**Comment by UltraNix** [comment]
The report was about the Black Arrow. I didn't know about Frost Trap.

**Comment by UltraNix** [comment]
@Soufly As I can see Frost Trap is described [here](https://github.com/GameFreedomGG/Sindragosa/issues/306) so it will be fixed once it is confirmed.
