### ISSUE TITLE
[Warlock][Talent] Demonic Pact + Totem of Wrath Interaction 

### ISSUE THREAD

**Issue by Whitemane-Calypso** [GameFreedomGG/Sindragosa#351]
Description :
There is a weird interaction between ToW and DP.
If a Totem of Wrath is placed before the pet crits an extra +28 sp is added to the next DP. Until being removed by the higher DP, Totem of Wrath should work as a buff increasing the base SP of the warlock by 280 so it does count in the next DP that removes the 280 Totem of Wrath buff but gains the 10% of it. 
Looking through old Wowhead Forum posts, this seems to be the case, with people even given the advice to cancelaura macro to get the ToW buff back to gain the extra SP. 
https://www.wowhead.com/forums/topic/132387#p1611419
Here is Asakawa talking about it, his word is trustworthy considering he is still a Dev for Blizzard to this day. 
But DP did not count into itself, so people back on retail had cancelaura macros to get the ToW buff back as to get the bonus SP.

How it works:
That is not what’s happening in game right now. ToW is not stacking at all. You have a Demo Warlock who has 5140 Spellpower, if ToW was stacking, the SP gain should be 540, but it’s not, it’s 514 a difference of 26 SP, and it’s not 28 due to rounding numbers.

How it should work:
The ToW should be calculated to your DP if the totem was down before your pet critted, and you should be able to /cancelaura DP to gain ToW buff of 28 SP for the next DP too.
 
Source (you should point out proofs of your report, please give us some source):
Given above.

**Comment by UltraNix** [comment]
@Whitemane-Calypso Let this clear out to me:
1. So let's say I have 2600 SP. I got ToW buff + 280, so I have now 2880SP. Now I got DP buff, which is 10% of my SP - so it's 288 SP. DP is stronger than ToW (280 vs 288), so ToW is getting removed. So my SP is now 2600 + 288 = 2888.
2. Now I got 2nd DP - it's again 10% of 2600 (not 2888, because next DP should not count my1st DP). So now it's 260 DP. MY total SP is 2600+ 260 = 2860. So the 2nd DP is weaker than the 1st one (288 vs 260). So in this wowhead comment they say it's better to remove the 1st DP, get again ToW and then get another DP, so ToW will count.
And this is how it should work, yes?
So now tell me how it works now on your core.

**Comment by Whitemane-Calypso** [comment]
Yes, what you described in 1/2 is precisely what should be happening, but it’s not. What’s happening right now is ToW buff doesn’t get applied to DP at all, so every warlock who gives DP to the raid gives it with 28 less SP than they should (if there is ele in raid ofc). And as for 3., no, if ToW is stronger than the SP gain from DP, ToW should remain and DP shouldn’t be applied.

**Comment by UltraNix** [comment]
Hmm, just tested with 0 SP. Got ToW (so now 280 SP). DP proc - now I have 309, so it looks like it works okay (at least for 0 base SP).
