### ISSUE TITLE
Yogg-Saron Bugs (25m)

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Sindragosa#388]
1. When phase 2 begins - two corruptor tentacles + one crusher tentacle + one constrictor tentacle spawns immediately.
**How it should work** - only 1 corruptor tentacle + 1 crusher + 1 constrictor should spawn at the start of phase, not two corruptor.

2. After a portal phase ends and the stun is done outside, a new crusher tentacle should immediately spawn. Right now, it is spawning on a different timer of some kind. See below video which illustrates proper tentacle spawn timers

3. When you use Hand of Protection on a player being grabbed by a constrictor tentacle, it should immediately free the player and kill off the tentacle, this does not currently happen (Source, first comment): 
https://www.wowhead.com/npc=33983/constrictor-tentacle#comments

4. Finally - the crusher tentacle seems to be hitting WAY too hard, it is not possible for a tank to go in to melee interrupt the "Diminishing Powers" cast it uses, they will likely get killed by 1 melee hit.

I did not notice any bugs on phase 1 or phase 3.

(Note: only did normal mode)

https://www.youtube.com/watch?v=0ZEJA52NrgI

**Comment by mrnuggets** [comment]
Hotfix (2009-05-14): "In the Yogg Saron encounter, Paladin Judgement spells will no longer cause Diminish Power from Crusher Tentacles to cease channeling."

**Comment by Soufly** [comment]
Since i cant do the fight currently i wanna help with the encounter:
1.Adds on yogg 0 should NOT be named ''marked'' ,just immortal guardians.
2.They should be not slowable,a.k.a kiting tactic wont work.
3.Yogg should cast shadow beacon on up to 5 guardians,not just 3.
PROFF:https://www.youtube.com/watch?v=0PSvwo3ZDZ4 frosthold realm first.

**Comment by Soufly** [comment]
Since i cant do the fight currently i wanna help with the encounter:
1.Adds on yogg 0 should NOT be named ''marked'' ,just immortal guardians.
2.They should be not slowable,a.k.a kiting tactic wont work.
3.Yogg should cast shadow beacon on up to 5 guardians,not just 3.
PROFF:https://www.youtube.com/watch?v=0PSvwo3ZDZ4 frosthold realm first.
4.Immortal guardians SHOULD cast drain life(this is important and makes the fight harder,cuz ''taunter'' the has to interrupt).
5.Players should not be able to [Blink], [Shadowstep], and Demonic Teleport while participating in the illusion events in the Yogg-Saron encounter.
6. Focus Anger, on Yogg-Saron’s Crusher tentacles, will result from pet attacks.
7. Death Ray hits players who are under the effect of Malady of the Mind
''Since the fight went live, there has been a hidden protection for players that prevents the casting of Psychosis and Malady of the Mind on targets with less than 30 Sanity. However, because Malady of the Mind has a slow missile speed and the hidden protection could take a second or two to apply, it was quite possible for the 30 sanity targeting threshold to be breached by these two random unavoidable effects.'' <<<<<<- check if this is also there.

**Comment by Godmatik** [comment]
We tested Yogg on PTR, the immortals were not able to be slowed and 3-5
were marked every time

**Comment by Godmatik** [comment]
Also - I conform that they are casting drain life and that death coiled
players are getting not by death rays. Can't comment on the other items you
listed

**Comment by Soufly** [comment]
https://sunwell-community.com/topic/15801-frosthold-secrets-of-ulduar-and-furious-gladiator-season-ulduar-difficulty/
So far only auriaya Hp is wrong(except the custom buffs on yogg/algalon) @Game-Freedom
