### ISSUE TITLE
[Dungeon][Heroic][CoS] The gate doesn't open after a wipe on Malganis (with players stuck between the two gates)

### ISSUE THREAD

**Issue by Lechy901** [GameFreedomGG/Sindragosa#402]
Decription:
After a wipe on malganis the two gates that lead to the boss don't open. We had some players stuck between the two gates. Not sure what would happen after starting it with Arthas again.

How it works:
The gate does not open back up after a wipe.

How it should work:
The gate should open after a wipe.

Source (you should point out proofs of your report, please give us some source):
My own experience.

**Comment by Lechy901** [comment]
Did you have a player between the two gates? Maybe that was the cause. In our case both the tank and healer were there :(

**Comment by UltraNix** [comment]
@Lechy901 Yes.

**Comment by danniellos94** [comment]
You can hit the last boss - Malganis after defeating him for a while. Arthas goes too fast on last phase and pulls everything.

https://www.youtube.com/watch?v=NylFvY3Nfeg 4:20 + malganis hp went to 100% after defeating him and he cant be hitted.

**Comment by UltraNix** [comment]
@danniellos94 Can you record that bug?

**Comment by danniellos94** [comment]
Yes,

https://www.youtube.com/watch?v=-ATeALW9tyo

Timestamps : 
1:53 + you need to be in range for Arthas to come - not sure if it's a bug but brann works the same way if you start the event somebody needs to follow him because he can bug out and will not come at all
6:37 escort event starting - see how Arthas ignore pulled mobs and go to the next wave? In weaker group it would cause an easy wipe
11:17 Malganis fight you can see I can hit him all the time after 0%.
Last thing I didn't recorded chromie animation it's looking great but she is coming after 20-30 seconds? She should be faster.

**Comment by UltraNix** [comment]
1. and 2. - not a bug. Arthas is set to defensive - attack only if he's attacked.
