### ISSUE TITLE
[Hunter][Pets]Pet Stuck in the air

### ISSUE THREAD

**Issue by parsafr0st** [GameFreedomGG/Sindragosa#413]
Decription: pet sticks in the air

How it works: So, i tested hunter's and mage's pet (elemental water) so far, when you are in the air and enter combat, your pet would get stick in the air, you can just check the video

https://www.mediafire.com/file/om7jznx181i8xvi/Wow_2022-01-18_15-18-27-468.mp4/file

How it should work: the pet should be able to get to the ground

Source (you should point out proofs of your report, please give us some source):

**Comment by Game-Freedom** [comment]
Okay, Just tested Water Elemental - it's kind of tricky, because it's clearly situational.

But in some cases, most likely when mob was aggroed by him, Elemental was slightly above the ground casting. But when aggro came to character and I moved a mob a little bit, Elemental was going down. It is a big buggy for sure.

https://streamable.com/rycf16

**Comment by parsafr0st** [comment]
> Okay, Just tested Water Elemental - it's kind of tricky, because it's clearly situational.
> 
> But in some cases, most likely when mob was aggroed by him, Elemental was slightly above the ground casting. But when aggro came to character and I moved a mob a little bit, Elemental was going down. It is a big buggy for sure.
> 
> https://streamable.com/rycf16

but u cant really compare the elemental with hunters pet, since the elemental is ranged
, but situations are kinda the same , i tested it many times
