### ISSUE TITLE
[Mage][Spell] Mirror Image

### ISSUE THREAD

**Issue by crittl** [GameFreedomGG/Sindragosa#428]
Description: Mirror images doesn't ignore threat when it is up. Mage can still pull aggro while mirror images are up.

How it works: Sometimes Mirror Images doesn't ignore threat and mage can still pull aggro.
![WoWScrnShot_012022_113633](https://user-images.githubusercontent.com/98115455/150392058-4113e85e-3473-45bf-895c-8d643047e310.jpg)
(in screenshot I pulled aggro from tank despite mirrors being still up)

How it should work: Mirror images should completely ignore threat while it is up (-90M threat temporarily) , and only transfer threat back to mage when it fades. 

Source (you should point out proofs of your report, please give us some source):
![image](https://user-images.githubusercontent.com/98115455/150407833-2efc26a6-8c43-4345-9b1c-36099d5dbd14.png)
![image](https://user-images.githubusercontent.com/98115455/150391002-6744278c-baff-4a90-b4b8-dae58b20ff0c.png)
https://www.mmo-champion.com/threads/965330-Mirror-Images-and-threat

**Comment by Soufly** [comment]
your link is from cataclysm,they also say that MI should give minus 9mln agro...

**Comment by crittl** [comment]
It's a temporary -90M threat while its up.
It's hard to find a thread from WOTLK but this evowow db link shows the same temporary aura.
https://wotlk.evowow.com/?spell=55342

**Comment by crittl** [comment]
I also found a video - you can see the mage pops Mirrors at start and goes up to 135% threat on LK but doesn't get targetted.
https://www.youtube.com/watch?v=2yS_fC9ti9w

**Comment by Soufly** [comment]
https://youtu.be/PJnZkKSwKEM?t=1 1800k threat on LK (omen)
https://youtu.be/PJnZkKSwKEM?t=99 3k threat on LK (omen)

**Comment by crittl** [comment]
^ He invis'd to reset threat - but the first video shows him going up to 169% threat on a raging spirit without pulling because of mirror image.

**Comment by Soufly** [comment]
Yeah just saw that

**Comment by Game-Freedom** [comment]
Just tested it out - that's confirmed bug. I reached 100-200% threat several times without mob changing target on me.

**Comment by UltraNix** [comment]
@Game-Freedom Tested on what mob? Could you provide steps to reproduce that bug?

**Comment by crittl** [comment]
@UltraNix I think I figured it out. If you mirror before hitting the mob yourself (e.g. with arcane blast), the mirror image's ignore threat mechanic doesn't work. If you watch the retail video, however, he mirrors before casting the first arcane blast and the ignore threat mechanic still works.

**Comment by UltraNix** [comment]
@crittl No. That threat reduction is applied when the Mirror Images are up, so it does not matter if the spell (Arcane Blast) already hit the target or not.
@Game-Freedom Still waiting for more info.

**Comment by crittl** [comment]
@UltraNix The problem is the threat reduction doesn't work unless you hit the target with a spell first. As shown on the picture - despite mirror images being up, I was still being hit by the mob.

**Comment by UltraNix** [comment]
@crittl Can you record that?

**Comment by crittl** [comment]
https://user-images.githubusercontent.com/98115455/153648662-27ea6bdf-72e1-41cb-a675-78fc7c89e9ca.mp4

**Comment by crittl** [comment]
https://user-images.githubusercontent.com/98115455/153648662-27ea6bdf-72e1-41cb-a675-78fc7c89e9ca.mp4

**Comment by crittl** [comment]
https://user-images.githubusercontent.com/98115455/153648662-27ea6bdf-72e1-41cb-a675-78fc7c89e9ca.mp4

**Comment by gitghost** [comment]
idk about you guys but that's how mirror images were working on every private server and they work fine
they can't reduce any threat if there is no threat

critlea look at your video, he cast mirror image 0.01 sec AFTER the pull, so they are already in threat table, if he would cast them before pull, they are just dps but completly no use in term of threat reductor

**Comment by crittl** [comment]
thats not how they worked on retail - they should ignore threat when up

**Comment by gitghost** [comment]
I have spend 2 hours just to prove a point. I discovered that counterspell is doing waaaay less threat that is suppose to do.
At least that's what i think. I won't call it a bug, i'm a mage and this bug is not so important to bother devs.

SO i made a test. I get a mage and a priest in a party.
On first try i cast renew on a mage and wait for last 2 ticks of the renew spell.
When there's only 2 ticks left of the renew i pull world mob with a counterspell of a mage.
First tick of renew hit, nothing is happening, second tick of renew hit, now aggro switches to priest.

On second try i do almost the same thing.
I cast renew on a mage and wait for last 2 ticks of the spell. This time i hit FADE, to reduce my threat.
I pull the mob with the counterspell.
First tick of renew hit, nothing is happening, second tick of renew hit, now aggro switches to priest.
Even tho fade spell is still on a priest.

We can agree that both fade and mirror image is broken or leave it as it is.
I know that both spells do this: Apply Aura: Mod Total Threat (Fade).
Aura is the same, but values are different. On a mage its -9M on a priest its -55.
If aura is the same so we can be sure that even tho on mage we can't see any icon, aura still applies.

The problem is this whole thing is programmed wrong.
Even tho it's called aura it is appied only on cast. Why? Because i think it's much easier to code.

Game is creating threat table every time combat starts. Now fade and mirror image are treated as simple spells.
If you cast them, they are only modyfing values in threat table. That's why now they are not working before combat.
U can't modyfie threat table values when there is no threat table yet.

I got two ideas how to fix it.
First idea is: every time combat starts, and threat table is created game need to check if there's a mage or priest with a fade or mirror image active, and then "cast" Apply Aura: Mod Total Threat (Fade). To put simply, cast spell again.
If so, you need to check how much time is left on the spell and extract that value from "second cast", so threat mod won't last longer than suppose to.
Second idea: create real spell aura that is cast with both spells. How that works?
NO IDEA.

To put simply, this bug is not worth the time and effort so u can click mirror image 1.5 sec before combat.
Even more simple: GIT GUD

**Comment by crittl** [comment]
@gitghost this is a bug report - it's not my job to judge whether it is worth the time and effort to fix, I'm merely pointing out a bug, and I think you agree with me that it's bugged. Whether it's fixed or not is not up to me.
