### ISSUE TITLE
[Ulduar] Flame Leviathan - Pursue target swap needs fixing

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Sindragosa#429]
The pursuit ability from Flame Leviathan encounter is targeting the correct vehicles now, but the timing of the target swap is not correct. It should be the following:

1.) Will target swap to different vehicle after 30 seconds of pursuing it's current vehicle
2.) If shutdown debuff is put on him, the timer will reset and he will target swap after it ends to a new vehicle for 30 seconds.
3.) If target vehicle is destroyed, he will target swap to a new vehicle for 30 seconds.

In particular, (2) does not seem to be working properly, and (1) needs to also be looked at.

Retail video: https://www.youtube.com/watch?v=7qQBFRn4K0Y

**Comment by Nessy27** [comment]
After looking at some videos, your #2 seems to be off. FL will continue following the target after Systems Shutdown if it is still within the 30sec pursue timer. For example, FL pursues a new target and 1 sec later is shutdown. After coming out of the shutdown, he will continue pursing the target for the remaining 9 sec until he casts it again.

Video: https://www.youtube.com/watch?v=00p_Ni58YGE at time 2:05

From what I can tell on Sindragosa, a Systems Shutdown will delay the pursue timer and also the flame vents timer for 20 sec. So in the example I made above, he would continue to pursue the target for 29 sec after shutdown.

**Comment by Godmatik** [comment]
The video I linked shows differently, unless Blizzard changed the pursue mechanic timing at some point.

https://www.youtube.com/watch?v=7qQBFRn4K0Y&t=50s

FL was put into shutdown mode but still had ~10 seconds left on his target, after shutdown ended, he immediately swapped over to a new target.

**Comment by Nessy27** [comment]
Your first point is right. If the timer for a new pursue target happens during a shutdown, he will then wait until shutdown has ended and immediately make a new pursue.

For the second one, it looks like he continues to pursue the target he was going for prior to the shutdown. It is hard to tell because of the delay to move again after shutdown (was like 2 sec) and the window to continue that original pursue was so small (less than a second). FL moves forward toward the previous target and then does some weird pathing and switches to the new target that is off screen to the left. But again, the pursue window is so small there that it is hard to tell if that is true.
The video I showed is easier to tell since there was like 5 seconds after shutdown that FL continued to pursue his original target.

**Comment by Godmatik** [comment]
Looked pretty clear to me... especially my 2nd link. He starts pursuing one target, shutdown happens 5 seconds into that pursuit, 1 second after shutdown he switches to new target, it also indicates the pursuit targets in the warning texts.

**Comment by Godmatik** [comment]
From changelog posted today:

"☑️ [Raid/Ulduar]: Improve pursue mechanic, will choose new target after shutdown, set timer to 30s (Flame Leviathan)."

I will go ahead and close this report, will re-open if it is not properly fixed
