### ISSUE TITLE
[Death Knight] 4-set t8 bonus

### ISSUE THREAD

**Issue by danniellos94** [GameFreedomGG/Sindragosa#472]
Decription:
4- set t8 bonus for dk seems not working. I used tomahawk for a tests axe 4-9 damage.
How it works:
With t8 set bonus https://prnt.sc/26mn3ga 1078 damage
Without t8 set bonus https://prnt.sc/26mn4al 1060 damage

Both tests without procs and with diseases on target.
Please note that difference is from 21 strength from my second legs.
I've check also obliterates and got the same results.

How it should work:
It should works and provide 20% damage of disease.

Source (you should point out proofs of your report, please give us some source):
UP.

**Comment by ClassicMage** [comment]
That tier bonus is tricky. It doesn't upgrade your damage by raw 20%. It is very minor upgrade of BONUS dmg from diseases. For example your scourge strike deals 12.5% bonus damage per disease. With tier bonus it is 12.5%*1.20 making bonus damage 15% (so it increases by raw 2.5% of disease). Since you tested low damage weapon the change may not be even noticable.

**Comment by danniellos94** [comment]
True seems like everything is fine right now its 1.24 multiplier with diseases.
