### ISSUE TITLE
[Death Knight] Death Rune Incorrect Prioritization

### ISSUE THREAD

**Issue by Oida123** [GameFreedomGG/Sindragosa#62]
DK's runes seem to be prioritized in a wrong order. I've tested several times now, that if I:

a) have 1 death rune op
b) use a spell (e.g. unbreakable armor) that require on frost rune
c) it uses a frost rune (not death rune)

This basically means that Frost rune spells will use frost runes before death runes until there are no more frost runes available.

**Comment by danniellos94** [comment]
https://www.warmane.com/bugtracker/report/105293 Same bug report from warmane.

**Comment by Oida123** [comment]
![image](https://user-images.githubusercontent.com/93870907/140659227-9bb021ee-0570-4686-8e43-8a400f7b1208.png)

**Comment by danniellos94** [comment]
"In simple terms:
+ // Let's say we use a skill that requires a Frost rune. This is the order:
+ // - Frost rune
+ // - Death rune, originally a Frost rune
+ // - Death rune, any kind"

**Comment by Supershappert** [comment]
FYI

Death Runes

If you spec Death Rune Mastery, Blood of the North or Reaping, upon using the specified abilities the Runes that they use up will regen into Death Runes. Death Runes are a 4th type of Rune which is able to be used as either a Blood, Frost or Unholy Rune. They only stay a Death Rune for one usage and in general you will only use up a Death Rune if none of the normal Runes are available to be used with an ability.

Say, for example you are specced into Death Rune Mastery and you have used Obliterate. The Frost & Unholy Rune will become Death Runes. However, you still have 2 Blood Runes, 1 Frost & 1 Unholy Rune left. If you let the Death Runes come up so that your Rune layout looks like BBFDUD and you want to BS twice, PS once and IT once, you will only use up BBFU, leaving you with DD. The Death Runes are always the last runes to be used.

As a side note, Blood Tap is the only non-talented ability that will give you access to a Death Rune.

It should be further noted that Death Rune Mastery works somewhat different from what you'd expect. If you have all your Unholy and Frost Runes as Death Runes (so BBDDDD), and then use an Obliterate or Death Strike, the following happens:

* [1] Your two Unholy Runes which are currently Death Runes will get used by the ability.
* [2] Only one of your recently used Death Runes will remain a Death Rune. The other will turn back to Unholy, despite having just been used for an ability. (Or BBDDDU)

If you have only your Unholy Runes as Death Runes, and your Frost Runes are currently on cooldown, thus making it that your two converted Unholy Runes get used by Obliterate or Death Strike (BBFFDD), the following happens:

* [1] Your two Unholy Runes which are currently Death Runes will get used by the ability.
[2] As before, only one of your two Unholy Runes becomes a Death Rune, however one of your Frost Runes (despite not being used by the ability) will also become a Death Rune. (BBDFDU)

That also applies if you have two Frost Runes as Death Runes and you use those for Obliterate or Death Strike. You end up with one of the Frost Runes staying a Death Rune, while one of the Unholy Runes will also turn into a Death Rune.

**Comment by UltraNix** [comment]
Works like @danniellos94 described.
